#!/usr/bin/env node
/**
 * `npm run verify:sweep`
 *
 * Re-diffs every corpus/sweep-* fixture (generated by generate-sweep.mjs)
 * against headless Chrome on all four layers and asserts each fixture's
 * RECORDED expectation still holds:
 *   - a fixture the generator marked `pass` must pass all four layers again;
 *   - a fixture the generator marked as a typed gap (expected.<layer>:
 *     { result:'fail', reason, sunset }) must STILL diverge on that layer.
 *
 * This is the anti-drift contract of the value-sweep: a divergence is recorded
 * in the fixture AND documented in docs/ledgers/sweep.md — never silently
 * excluded. If a documented divergence closes (starts passing), verify fails
 * and the fixture must be reclassified into the pass corpus.
 *
 * Exits 0 only when every swept fixture's recorded expectation holds.
 */

import { chromium } from 'playwright';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { loadTolerances } from '../dist/harness/tolerances.js';
import { decodePng, encodePng } from '../dist/harness/png.js';
import { evaluateFixture } from '../dist/harness/evaluate.js';
import { buildReport, writeReport, renderMarkdown } from '../dist/harness/report.js';
import { renderHtml } from '../dist/layout/render.js';
import { isGapExpectation } from './lib/expected.mjs';
import { FLEX_AXES, GRID_AXES } from './lib/sweep.mjs';
const FONT_FILE = process.env.FONT_FILE ?? '/usr/share/fonts/google-noto/NotoSans-Regular.ttf';
const FONT_FAMILY = process.env.FONT_FAMILY ?? 'Noto Sans';

const ledgerPath = resolve('docs/ledgers/sweep.md');

function* fixtures(root) {
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = join(root, entry.name);
    const fpath = join(dir, 'fixture.json');
    if (!statSync(fpath, { throwIfNoEntry: false })?.isFile()) continue;
    yield { dir, name: entry.name, raw: JSON.parse(readFileSync(fpath, 'utf8')) };
  }
}

const tolerances = loadTolerances(resolve('tolerances.json'));
const browser = await chromium.launch();
const results = [];
const rows = [];

try {
  for (const featureDir of ['flexbox', 'grid']) {
    const root = resolve(`corpus/sweep-${featureDir}`);
    if (!statSync(root, { throwIfNoEntry: false })?.isDirectory()) {
      console.error(`verify:sweep: corpus directory missing: ${root}`);
      process.exit(1);
    }
    for (const { dir, name, raw } of fixtures(root)) {
      const h = raw.harvest;
      const viewport = h.viewport;
      const page = await browser.newPage({ viewport: { width: viewport.width, height: viewport.height } });
      await page.setContent(h.html);
      await page.evaluate(() => document.fonts.ready);

      const referenceRects = {};
      for (const id of h.rects ?? []) {
        referenceRects[id] = await page.$eval(`#${id}`, (el) => {
          const r = el.getBoundingClientRect();
          return { x: r.x, y: r.y, width: r.width, height: r.height };
        });
      }
      const shot = await page.screenshot();
      const refImg = decodePng(shot);
      const { width, height } = refImg;
      await page.close();

      const out = renderHtml(h.html, {
        width: viewport.width,
        height: viewport.height,
        fontFamily: FONT_FAMILY,
        fontFile: FONT_FILE,
      });
      const candImg = decodePng(out.rgba);

      // Persist the corpus golden data (same values the generator wrote).
      writeFileSync(
        join(dir, 'reference.json'),
        JSON.stringify({ measureText: {}, computedStyle: {}, rect: referenceRects }, null, 2) + '\n',
      );
      writeFileSync(
        join(dir, 'candidate.json'),
        JSON.stringify({ measureText: {}, computedStyle: {}, rect: out.rects }, null, 2) + '\n',
      );
      writeFileSync(join(dir, 'reference.png'), shot);
      writeFileSync(join(dir, 'candidate.png'), encodePng(candImg.width, candImg.height, candImg.data));

      const fixture = {
        name,
        note: raw.note,
        expected: raw.expected ?? {
          measureText: 'pass',
          computedStyle: 'pass',
          rect: 'pass',
          screenshot: 'pass',
        },
        tolerances,
        referenceRgba: refImg.data,
        candidateRgba: candImg.data,
        mask: null,
        reference: { measureText: {}, computedStyle: {}, rect: referenceRects },
        candidate: { measureText: {}, computedStyle: {}, rect: out.rects },
        width,
        height,
      };

      const result = evaluateFixture(fixture);
      results.push(result);
      const rectLayer = result.layers.rect;
      const shotLayer = result.layers.screenshot;
      const gapLayers = ['rect', 'screenshot'].filter((l) => isGapExpectation(raw.expected?.[l]));
      rows.push({
        fixture: name,
        feature: featureDir,
        pass: result.checkPass,
        gap: gapLayers.length > 0,
        gapLayers,
        rectMaxDelta: rectLayer.maxDelta,
        screenshotExceedPct: shotLayer.percentExceeding,
      });
      console.log(
        `verified ${name} (${featureDir}): ${result.checkPass ? 'PASS' : 'FAIL'} — rect max Δ ${rectLayer.maxDelta.toFixed(3)}px, screenshot ${shotLayer.exceedingPixels} exceeding (${shotLayer.percentExceeding.toFixed(3)}%)`,
      );
    }
  }
} finally {
  await browser.close();
}

// --- ledger: axes, per-fixture results, and every recorded divergence ---
{
  const gaps = rows.filter((r) => r.gap);
  const md = [];
  md.push('# Value-Sweep Ledger');
  md.push('');
  md.push(
    'Programmatic breadth for the charter §11 coverage matrix: `scripts/generate-sweep.mjs` sweeps property/value axes, generates one fixture per combination into `corpus/sweep-flexbox/` and `corpus/sweep-grid/`, and records each combo\'s measured parity. `npm run verify:sweep` re-diffs all four layers against Chrome and asserts the recorded expectations still hold. Nothing here is hand-authored.',
  );
  md.push('');
  md.push('## Axes');
  md.push('');
  md.push('- **flex-wrap**: ' + FLEX_AXES['flex-wrap'].join(', '));
  md.push('- **justify-content**: ' + FLEX_AXES['justify-content'].join(', '));
  md.push('- **align-items**: ' + FLEX_AXES['align-items'].join(', '));
  md.push('- **grid-template-columns**: ' + GRID_AXES['grid-template-columns'].join(' ; '));
  md.push('- **gap**: ' + GRID_AXES.gap.join(', '));
  md.push('');
  md.push('## Latest Run');
  md.push('');
  md.push(`- Generated: ${new Date().toISOString()}`);
  md.push(`- Fixtures swept: ${results.length}`);
  md.push(`- Passing: ${rows.filter((r) => !r.gap).length}`);
  md.push(`- Documented divergences (typed gaps, still diverging): ${gaps.length}`);
  md.push('');
  md.push('## Swept Fixtures');
  md.push('');
  md.push('| Fixture | Feature | Expected | Gap layers | Rect max Δ px | Screenshot exceed % | Result |');
  md.push('|---|---|---|---|---|---|---|');
  for (const r of rows) {
    md.push(`| ${r.fixture} | ${r.feature} | ${r.gap ? 'gap' : 'pass'} | ${r.gapLayers.join(', ') || '-'} | ${r.rectMaxDelta.toFixed(3)} | ${r.screenshotExceedPct.toFixed(4)} | ${r.pass ? 'PASS' : 'FAIL'} |`);
  }
  md.push('');
  md.push('## Known Divergences (documented, not silently excluded)');
  md.push('');
  md.push(
    'Fixtures whose generator run recorded a divergence carry a typed gap on the diverging layer(s) (`expected.<layer>: { result:"fail", reason, sunset }`) and are listed here. The verify script asserts each still diverges, so a divergence that closes fails the run and must be reclassified into the pass corpus.',
  );
  md.push('');
  for (const g of rows.filter((r) => r.gap)) {
    md.push(`- **${g.fixture}** — gap on ${g.gapLayers.join(', ')}; rect max Δ ${g.rectMaxDelta.toFixed(3)}px, screenshot ${g.screenshotExceedPct.toFixed(4)}% exceeding.`);
  }
  md.push('');
  writeFileSync(ledgerPath, md.join('\n') + '\n');
}

const report = buildReport(results, { fixtureSet: 'corpus/sweep-*', tolerancesVersion: tolerances.version });
const outDir = writeReport(report);
console.log(renderMarkdown(report));
const ok = report.allChecksPass;
console.log(ok ? `PASS: sweep report written to ${outDir}` : `FAIL: sweep report written to ${outDir}`);
process.exit(ok ? 0 : 1);
